apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: il2y0b3fu-python 
  janus-idp.io/tekton: il2y0b3fu-python
  backstage.io/kubernetes-id: il2y0b3fu-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: il2y0b3fu-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  