apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: il2y0b3fu-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:45091e6eb53a5e9a81782d400c475d181eaa6ccb@sha256:aa84f87eadc3875a4d3b8593cbaddfbd5659cc99b70db9e6d1dd9c92f2b0ca27
          name: container-image
